- README.md
I am an author, editor and developer trying to help Swift achieve world domination. As an educator, I focus mostly on open source teaching materials and tools used in education.
> Added Steven Van Impe

- README.md
Thank you for considering merging this PR.
> Added Franck Nijhof as someone doing opensource work

- README.md
Hey there! I'm a software engineer residing in Surat, Gujarat, India, with a focus on creating open-source apps for web as well as mobile devices. You can know about me here: https://www.amitmerchant.com
Regards.
> Add Amit Merchant

- README.md
Hi,
I create javascript plugins or projects related to Bootstrap (or not) and I'm a part of Bootstrap's team as JavaScript developer.
> Add Johann-S

- README.md
- Adding Asset-Importer-Lib ( see http://assimp.org/ and https://github.com/assimp/assimp )
> Add assimp to list.

- README.md
The Patreon pages of these people are not the official donation channels of the projects they were under. Also corrected some descriptions.
> Moved a bunch of folks from Projects to People

- README.md
People: Andreas Kainz, Sam Hewitt, Kurt Kremitzki, Nate Graham, Jehan Pagès, Rob Landley, Timothée Giet, Scott Lahteine, Dave Täht, Dominik Honnef, Ondřej Surý, Fabio Zadrozny, Marc Jeanmougin
Operating systems: Ubuntu Touch, Antergos, Linux Lite, GhostBSD
Projects: OctoPrint, HaxeUI, Dear ImGui, MuseScore, PlantUML, Synfig, Paperwork
Libraries and frameworks: Laravel
> Added some fine folks and projects

- README.md
Put the new multiple funding sources guidelines into practice.
Added the subscription funding links for Armory, Blender and FreeCAD.
Added OfBorg to projects.
Added Alyssa Ross.
Moved ZeMarmot to the new open source art category (was listed under Jehan Pagès earlier).
Corrected operating systems anchor link.
> More funding sources, additions, tweaks

- README.md
Added entry for SysV init implementation
> Added software project sysvinit

- README.md
Added DistroWatch for its open source, Linux and BSD tutorials and articles.
> Added article entry

- README.md
Nethack, GPSd, Author of "The Cathedral and The Bazaar", coined the term "Linus's Law", etc.
> Added Eric S Raymond to the list

- README.md
Also add Liberapay link for Mastodon.
> Add Lutris, Matrix and Xenia

- README.md
Projects: Neovim, Perkeep, Webpack, Xfce
Libraries: Phalcon
Flarum moved as a project from Patreon to OpenCollective and individual devs set up Patreon accounts.
> More additions and tweaks

- README.md
People: JeanHeyd Meneide
Projects: Albert launcher, LibrePCB
> Added 3 entries

- README.md
My surname is "Rosenzweig", not "Ross". Additionally, I'm not involved with NixOS.
> Correct my entry

- README.md
People: Andrea Ferrero, Reini Urban
Projects: ApexCharts, Open Source BIM Collective, Tabulator
> Added some people and projects

- README.md
Projects: Akira, Latte Dock, MissKey, NativeScript-Vue, PixelFed
People: Jacky Alcine (repos: https://git.jacky.wtf/indieweb ), Kevin Cozens, Philip Guo (Python Tutor repo: https://github.com/pgbovine/OnlinePythonTutor )
Tutorials: Kyle Simpson
> More people and projects

- README.md
People:
Andrius Štikonas, Jacky Alcine, skypjack, Stjepan Glavina
Projects:
Duplicati, Lollipop Cloud, Olive, Open Broadcaster Software, openage, phpMyAdmin, Prismo, ReactOS, Zig
I hope Jacky can be accepted now that Koype has a website:
https://koype.net/
Latest news: https://v2.jacky.wtf/post/2019-may-koype
> Added people and projects

- README.md
> Add Invidious: alternative web front-end to YouTube.

- README.md
> Adding Jam.py

- README.md
> Fix typo in "Symfony"

- README.md
Pica Pica is my personal long-term (11+ year) project aimed to provide the software for cross-platform decentralized and encrypted communication. Now it provides ability to exchange text messages and files with end-to-end encryption, and with some funding I hope to implement voice and video calls, mobile clients, message history synchronization over multiple devices and many other exciting features.
> Add Pica Pica Messenger project

- README.md
> Update Feross info

- README.md
Project links:
-   <https://stdlib.io>
-   <https://github.com/stdlib-js/stdlib>
> Add funding link for stdlib

- README.md
Just merge it.
The money was lost.
> Remove vvctre

- README.md
Contains both open source art and software, more ways to support the project found at the repo under sponsors: https://github.com/kitbashery/Kitbashery
> Added kitbashery

- README.md
I read it's allowed to add own projects if they meet the criteria. The project's github: https://github.com/asc-community/AngouriMath. Does it meet them?
> Adding my project?

- README.md
Removed:
- Amit Merchant
- Arxiv Insights
- byuu
- Devon Crawford
- Flare3D
- Future of Coding
- Jam.py
- JustForFunc
- Machine Labs
- OfBorg
- OMP
- Oni (the license is not open source)
- Philip Guo
- Pica Pica Messenger
- Pierre Krieger
- Prismo
- Sam Hewitt
- Software Defined Talk
- Stjepan Glavina
- Tanu Kaskinen
- The Development Hell Podcast
- Toby Zerner
- Zer0Mem0ry
Updated:
- ApexCharts
- Attogram Project
- Dear ImGui
- Hapi.js
- Invidious
- Johann-S
- Open Source BIM Collective
- PHPUnit
- Raph Levien
- Scarlett Clark (surname)
- skypjack
- Thirty Bees
- Vim-Go
> Removals and updates

- README.md
People: Andreas Heinisch, Flammie, René Rebe
Projects: BookWyrm, Zrythm
> Add new people and projects

- README.md
Repo: https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator - MIT Licensed
Live: https://eigengrausgenerator.com 
Patreon: https://patreon.com/eigengrausgenerator
> Add Eigengrau's Generator

- README.md
The "Open Source Projects" category is so big it's getting hard to read. A new category will help a bit.
> Create a new category for messaging and social media
